languageCode = "en-us"
title = "Front"
baseurl = "https://mandrakecqc.github.io/front-page/"
theme = "aerial"

[params]
  name = "Keren Chen"
  about = "Computer Science Undergrad"
  copyright = "Untitled"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = ""
  favicon = "favicon.ico"

[[params.social]]
  medium = "Twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://github.com/MandrakeCQC"

[[params.social]]
  medium = "Email"
  icon = "envelope-o"
  link = "kerench43@yahoo.com"

[[params.social]]
  medium = "Professional"
  icon = "briefcase"
  link = "#"

[[params.social]]
  medium = "Personal"
  icon = "coffee"
  link = "#"